### ISSUE TITLE
Failed to initialize in 2022.7.2

### ISSUE THREAD

**Issue by Bredin76** [snarky-snark/home-assistant-variables#79]
Hi, 

Variables 0.14.2 failed to initialize in HA 2022.7.2
Tried to reinstall, also tried to install development branch in case of the thing was the same as #78 but nothing.

just  got that log `Setup failed for custom integration var: Integration failed to initialize.`

regards

**Comment by fprokop** [comment]
Same here. Here's a detailed log:
`Setup failed for custom integration var: Unable to import component: cannot import name 'Events' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py)`

**Comment by MaikB1972** [comment]
Hi, I had the same bug. After upgrading HA to 2022.7.3 and variables 14.2, the bug is gone and it works again

**Comment by Bredin76** [comment]
I can confirm, Updating Home assistant in 2022.7.3 and variables in 14.2 solve the problem.

**Comment by georg90** [comment]
For me this still throws an error, when trying to use the component
`Component error: var - cannot import name 'Events' from 'homeassistant.components.recorder.models' (/usr/src/homeassistant/homeassistant/components/recorder/models.py)`

I am running HA 2022.7.7 with Variable v15.0, v14.2, develop => Always the same error message.

Can we reopen or should I create a new issue? Maybe it's more related to #78

**Comment by georg90** [comment]
My bad, I had the old installation interfering.. It's working now with latest development version.
